# Generated by Django 4.2.7 on 2025-10-06 19:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dataset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "disease_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("sample_size", models.IntegerField(blank=True, null=True)),
                (
                    "data_accessibility",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "wgs_available",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "imaging_types",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("modalities", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Publication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("authors", models.TextField(blank=True, null=True)),
                ("journal", models.CharField(blank=True, max_length=200, null=True)),
                ("year", models.IntegerField(blank=True, null=True)),
                ("pmid", models.CharField(blank=True, max_length=20, null=True)),
                ("doi", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "dataset_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["-year", "-created_at"],
            },
        ),
    ]
